#!/bin/bash

gh api notifications --paginate --jq '.[] | [.subject.url,.subject.type,.url] | @tsv' | while read -r URL TYPE THREAD_URL; do
    if [[ $TYPE == "Commit" ]]; then
        continue
    fi
    
    ITEM=$(gh api $URL)
    NUMBER=$(jq -r .number <<< ${ITEM})
    TITLE=$(jq -r .title <<< ${ITEM})
    STATE=$(jq -r .state <<< ${ITEM})

    if [[ "$STATE" != "null" ]]; then
        printf '%-10s is %s\n' "$TITLE" $STATE 

        if [[ "$STATE" == "closed" ]]; then
            echo "  Marking closed item as read: $THREAD_URL"
            gh api -X PATCH $THREAD_URL
        fi
    fi
done